# Generated by Django 2.1.2 on 2018-11-13 08:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipes',
            name='ingredient1',
        ),
        migrations.RemoveField(
            model_name='recipes',
            name='ingredient2',
        ),
        migrations.RemoveField(
            model_name='recipes',
            name='ingredient3',
        ),
        migrations.RemoveField(
            model_name='recipes',
            name='ingredient4',
        ),
        migrations.RemoveField(
            model_name='recipes',
            name='ingredient5',
        ),
        migrations.AddField(
            model_name='recipes',
            name='ingredients',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
