# Generated by Django 2.1.2 on 2018-11-15 08:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_auto_20181113_0801'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipes',
            name='date_posted',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
